#!/usr/bin/env bash
# Made by EvdH, no warranty just YOLO!

# Sends a command to xscreensaver to lock, suspend after success.
waylock -fork-on-lock -ignore-empty-password -init-color 0xFF5555 -input-color 0x0060BB && systemctl suspend


